# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojsten_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='structure',
            field=models.CharField(default='[]', max_length=200000),
        ),
    ]
